### ISSUE TITLE
Clean up of inactive members July

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/org#2013]
This is the list of [inactive members](https://github.com/kubernetes/community/blob/master/communitymembership.md#inactive-members) that are slated to be removed from our Github Orgs. They have had no devstats recorded activity since the release of v1.11.

**Note:** the default devstats dashboards only reflect contributions above a certain threshold (>5). The data used for this list was obtained separately through 2 requests made to the cncf/devstats project (ref: https://github.com/cncf/devstats/issues/243 / https://github.com/cncf/devstats/issues/254).

Clean up of the owners files can begin immediately, but removal of members should be held off till July 17th giving people time to ack and notice to sent to k-dev.

ref: https://github.com/kubernetes/community/issues/3179

---
**Members to be removed**
- @abiogenesis-now
- @adamreese (owner)
- @ajitak
- @aknuds1
- @alexandercampbell
- @almogbaku
- @amey-d
- @andreykurilin
- @andronat
- @asultan001
- @avinassh
- @bdbauer
- @bencer
- @bgrant0607-cc
- @bgrant0607-nocc
- @bmelville
- @bprashanth (owner)
- @bsherman
- @burmanm
- @cab105
- @cameronbrunner
- @carrodher
- @chrisglass
- @christian-roggia
- @colhom
- @crassirostris
- @cupofcat (owner)
- @czahedi
- @danpaik
- @derekparker
- @dhilipkumars
- @djkonro
- @dmmcquay
- @dnardo (owner)
- @drinktee
- @dshulyak
- @dubstack
- @ebbeelsborg
- @eghobo
- @elg0nz
- @emaildanwilson
- @emsearcy
- @ezeev
- @fabianofranz
- @fabioy
- @fgrzadkowski
- @flavio
- @frostman
- @gabrtv
- @ganeshspatil
- @ghodss
- @gluke77
- @grahamawelch-zz
- @gsasha
- @gtank
- @hardysimpson
- @hodovska
- @hongbin
- @hui-zhi
- @hw-qiaolei
- @icereval
- @ikester
- @it2afl0rd
- @itayariel
- @iterion
- @jamiehannaford
- @jbhurat
- @jcbsmpsn
- @jdavis7257
- @jiangtianli
- @jiangyaoguo
- @johanatan
- @johnwilkes
- @josvazg
- @jsoriano
- @jszczepkowski
- @juan131
- @juliaferraioli
- @kgrygiel
- @kokhang
- @lazypower
- @linfan
- @lukasredynk
- @lukemarsden (owner)
- @luomiao (owner)
- @markturansky
- @matchstick (owner)
- @mattf
- @mattthias
- @mbruzek
- @mburke5678
- @mdelio
- @mgr01
- @mhenc (owner)
- @mijajasinski
- @mike-saparov
- @mikejeffrey
- @mikejihbe
- @mikeln
- @mlaccetti
- @monadic
- @mqliang (owner)
- @nhlfr
- @olekzabl (owner)
- @pbx0
- @pewu (owner)
- @philroche
- @pipejakob (owner)
- @pokoli
- @pospispa
- @prashima
- @preillyme
- @procrypt
- @pshahzeb
- @q-lee (owner)
- @ramr
- @rcj4747
- @rjkernick
- @rjnagal
- @rjog
- @ronnielai
- @rrati (owner)
- @rrmckinley
- @sameersbn
- @sarahkconway (owner)
- @satnam6502
- @seanknox
- @sebastianm
- @shaominchen
- @shiliangxue
- @shtatfeld
- @sparkprime
- @sylwekb
- @timstclair
- @tmrts
- @tompizmor
- @totherme (owner)
- @varshavaradarajan
- @vefimova
- @venilnoronha
- @vmarmol
- @willb
- @william-tran
- @xsgordon
- @yinghan
- @zen
- @zhill

**Repos where inactive owners will need to be updated:**
- [x] [kubernetes/api](https://github.com/kubernetes/api) - kubernetes/kubernetes#92987
  - mqliang
- [x] [kubernetes/apimachinery](https://github.com/kubernetes/apimachinery) - kubernetes/kubernetes#92987
  - mqliang
- [x] [kubernetes/apiserver](https://github.com/kubernetes/apiserver) - kubernetes/kubernetes#92987
  - mqliang
  - rrati
- [x] [kubernetes/client-go](https://github.com/kubernetes/client-go) - kubernetes/kubernetes#92987
  - mqliang
- [x] [kubernetes/cloud-provider-gcp](https://github.com/kubernetes/cloud-provider-gcp) - https://github.com/kubernetes/cloud-provider-gcp/pull/156
  - dnardo 
- [x] [kubernetes/community](https://github.com/kubernetes/community) - https://github.com/kubernetes/community/pull/4932
  - pipejakob
- [x] [kubernetes/dashboard](https://github.com/kubernetes/dashboard) - https://github.com/kubernetes/dashboard/pull/5359
  - cupofcat
  - mhenc
  - olekzabl
  - pewu 
- [x] [kubernetes/k8s.io](https://github.com/kubernetes/k8s.io) - https://github.com/kubernetes/k8s.io/pull/1015
  - dnardo
- [x] [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) - kubernetes/kubernetes#92987, kubernetes/kubernetes#92988, kubernetes/kubernetes#92990
  - bprashanth
  - mqliang
  - q-lee
  - rrati
- [x] [kubernetes/test-infra](https://github.com/kubernetes/test-infra) - https://github.com/kubernetes/test-infra/pull/18286, https://github.com/kubernetes/test-infra/pull/18285
  - luomiao
  - totherme
- [x] [kubernetes/website](https://github.com/kubernetes/website) - https://github.com/kubernetes/website/pull/22474, https://github.com/kubernetes/website/pull/22475
  - lukemarsden
  - sarahkconway
- [x] [kubernetes-sigs/application](https://github.com/kubernetes-sigs/application) - https://github.com/kubernetes-sigs/application/pull/201
  - adamreese
- [x] [kubernetes-sigs/cloud-provider-baiducloud](https://github.com/kubernetes-sigs/cloud-provider-baiducloud) - https://github.com/kubernetes-sigs/cloud-provider-baiducloud/pull/123
  - matchstick
- [x] [kubernetes-sigs/cluster-proportional-vertical-autoscaler](https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler) - https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler/pull/38
  - dnardo
- [x] [kubernetes-sigs/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) - https://github.com/kubernetes-sigs/controller-runtime/pull/1045
  - totherme
- [x] [kubernetes-sigs/ip-masq-agent](https://github.com/kubernetes-sigs/ip-masq-agent) - https://github.com/kubernetes-sigs/ip-masq-agent/pull/55
  - dnardo

/area github-membership

**Comment by mrbobbytables** [comment]
It looks like you can only ping 50 users per comment. Here are the next 50.

- @ganeshspatil
- @ghodss
- @gluke77
- @grahamawelch-zz
- @gsasha
- @gtank
- @hardysimpson
- @hodovska
- @hongbin
- @hui-zhi
- @hw-qiaolei
- @icereval
- @ikester
- @it2afl0rd
- @itayariel
- @iterion
- @jamiehannaford
- @jbhurat
- @jcbsmpsn
- @jdavis7257
- @jiangtianli
- @jiangyaoguo
- @johanatan
- @johnwilkes
- @josvazg
- @jsoriano
- @jszczepkowski
- @juan131
- @juliaferraioli
- @kgrygiel
- @kokhang
- @lazypower
- @linfan
- @lukasredynk
- @lukemarsden (owner)
- @luomiao (owner)
- @markturansky
- @matchstick (owner)
- @mattf
- @mattthias
- @mbruzek
- @mburke5678
- @mdelio
- @mgr01
- @mhenc (owner)
- @mijajasinski
- @mike-saparov
- @mikejeffrey
- @mikejihbe
- @mikeln

**Comment by mrbobbytables** [comment]
Last batch
- @mlaccetti
- @monadic
- @mqliang (owner)
- @nhlfr
- @olekzabl (owner)
- @pbx0
- @pewu (owner)
- @philroche
- @pipejakob (owner)
- @pokoli
- @pospispa
- @prashima
- @preillyme
- @procrypt
- @pshahzeb
- @q-lee (owner)
- @ramr
- @rcj4747
- @rjkernick
- @rjnagal
- @rjog
- @ronnielai
- @rrati (owner)
- @rrmckinley
- @sameersbn
- @sarahkconway (owner)
- @satnam6502
- @seanknox
- @sebastianm
- @shaominchen
- @shiliangxue
- @shtatfeld
- @sparkprime
- @sylwekb
- @timstclair
- @tmrts
- @tompizmor
- @totherme (owner)
- @varshavaradarajan
- @vefimova
- @venilnoronha
- @vmarmol
- @wattsteve
- @willb
- @william-tran
- @xsgordon
- @yinghan
- @zen
- @zhill

**Comment by johnwilkes** [comment]
Hi.
What information do you wish to impart?
What actions do you wish us to take?

**Comment by johanatan** [comment]
My default action was going to be to ignore. :)

**Comment by mrbobbytables** [comment]
You can ignore if you're no longer involved with the project.
We're trying to clean up those that haven't been actively involved in the project for some time as being an org member grants a set of elevated permissions. 

Our means to detect inactive members doesn't take into account if you're active within the project in other means (non-code like helping with events, moderate things like slack), if you are, we can remove you from the list of members to be removed. 👍

**Comment by cab105** [comment]
Does this apply to the incubator projects as well? Granted I haven't been involved with kompose/kmachine in quite a while.

**Comment by mrbobbytables** [comment]
@cab105 its across all orgs and the incubator org itself will soon be archived. At this time, there are only 2 repos left in incubator with 1 being migrated to kubernetes-sigs and the other is slated to be archived once a component of it is moved out.

**Comment by mbruzek** [comment]
I am still active.

Matt Bruzek

**Comment by mrbobbytables** [comment]
@mbruzek can you link to some examples please? It doesn't have to be commits or PRs, but how any areas your helping with the upstream project.

**Comment by AlmogBaku** [comment]
I'd like to stay active. Recently I have more time to contribute

**Comment by mrbobbytables** [comment]
@AlmogBaku the project has changed significantly since 2016/2017 - In this instance, we'd prefer you go through the org membership process again. It's been streamlined and would require opening an issue in this repository after becoming active again. For more information check out our [community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md).

**Comment by nikhita** [comment]
All PRs for cleaning up OWNERS have merged. Closing.
