### ISSUE TITLE
REQUEST: Archive repo kubernetes-sigs/sig-usability

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/org#4295]
### Repository to archive

[kubernetes-sigs/sig-usability](https://github.com/kubernetes-sigs/sig-usability)

### Repository and/or sig subproject owners that are approving this archival

SIG Usability Leads

### When should this be done

Anytime

### Additional context for request

SIG Usability is being spun down. Ref: https://github.com/kubernetes/community/issues/7119

```[tasklist]
### Tasks
- [x] Ownership of the repo is transferred to the [kubernetes-retired](https://github.com/kubernetes-retired) GitHub organization
- [x] The repo description is edited to start with the phrase "[EOL]"
- [x] All open issues and PRs are closed
- [x] All external collaborators are removed
- [x] All webhooks, apps, integrations or services are removed
- [x] ~GitHub Pages are disabled~
- [x] Remove all teams associated with the repo (https://github.com/kubernetes/org/pull/4296)
- [x] The repo is marked as archived using [GitHub's archive feature](https://help.github.com/articles/archiving-a-github-repository/)
- [x] Remove the repo from sigs.yaml (https://github.com/kubernetes/community/pull/7365)
- [x] The removal is announced on the kubernetes-dev mailing list and community meeting (It will be announced as a subsequent email to the archival message)
```

**Comment by palnabarun** [comment]
/close

All items done!
