### ISSUE TITLE
Cleanup Kubernetes GitHub organizations - Jan 2024

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/org#4726]
An org membership grants one access to an elevated set of permissions, and many members also grow to be owners of code. Being inactive for a long period of time impacts the project. We have a [policy](https://github.com/kubernetes/community/blob/master/community-membership.md#inactive-members) for defining who is an inactive member. In the past, we have periodically cleaned up inactive members from our several GitHub organizations.

Last year, we made some [amendments](https://github.com/kubernetes/community/pull/7380) to our guidelines for inactivity, notably reducing the period for measurement of inactivity to 12 months.

Previous Instances of cleanup: https://github.com/kubernetes/org/issues/2456, https://github.com/kubernetes/org/issues/2076

If you find yourself in the below list and contribute actively in an area not captured by Devstats, please comment here with details about your contributions. The deadline for exceptions is February 12, 2024. If you miss raising an exception, one can initiate a revert of their removal from the repo.

Following is the list of inactive members who are slated to be removed from the Kubernetes GitHub organizations:

```
AGMETEOR
AdamDang
Adirio
AlexeyPerevalov
Amotul-raheem
AndyXiangLi
Arvinderpal
BaluDontu
Birdrock
Bradamant3
Bubblemelon
CKchen0726
CaoDonghui123
ChandaniM123
ChiefAlexander
CindyXing
ClaudiaJKang
ConnorDoyle
Cweiping
Cynerva
DaiHao
Damans227
DanyC97
EleanorRigby
EmilyM1
EppO
G-Harmon
Garima-Negi
GinnyJI
Jerry-Ge
JieJhih
JohnTitor
KashifSaadat
KentaTada
KimDoubleB
KofClubs
Lion-Wei
Liujingfang1
Lp-Francois
LuckySB
MAKOSCAFEE
MHBauer
MJ-CJM
MarcusNoble
MaxRenaud
Miouge1
Monkeyanator
MonzElmasry
NayeonKeum
NickrenREN
NicoleYson
NilimaC04
Nivedita-coder
OddBloke
PatrickLang
Pensu
Phillels
Potapy4
Pothulapati
PriyankaH21
Promaethius
PurneswarPrasad
QiWang19
RCantw3ll
Rajakavitha1
Rajat-0
RenaudWasTaken
RobertKrawitz
SEJeff
ScorpioCPH
ScrapCodes
Shell32-Natsu
SlickNik
SyamSundarKirubakaran
TommyLike
VineethReddy02
VivekThrivikraman-est
WanLinghao
WilliamDenniss
Xenwar
YangLu1031
Ye-Tian-Zero
YoubingLi
YuviGold
ZP-AlwaysWin
a-robinson
aaron-prindle
aaronbbrown
aaronlevy
aartij17
aasmall
abgworrall
abhisheksinghbaghel
abuisine
aditya-konarde
adohe
ahmad-diaa
aimeeu
ainmosni
aisonaku
alberthuang24
alejandrox1
alenkacz
alexbrand
alexgervais
alijahnas
alisondy
alonyb
alrs
ams0
amwat
amy
anastyakulyk
andrewrynhard
andriyDev
animeshsingh
ankeesler
annajung
answer1991
anthonydahanne
anthonyrtong
antoineco
aravindputrevu
arghya88
aronchick
arthurdm
arun-gupta
asalkeld
ashcrow
ashish-amarnath
asim-reza
astrieanna
avidLearnerInProgress
awesomenix
awkif
awly
ayberk
azhao155
b01901143
bai
balopat
bang9211
bartsmykla
bharath-123
bigkraig
bluebreezecf
blueelvis
bmelbourne
boddumanohar
boluisa
brahmaroutu
brett-elliott
bruceauyeung
butuzov
calebamiles
calvh
carlisia
carlosedp
carolinar7
carolynvs
cartyc
cathchu
cccswann-godaddy
celanthe
cgilmour
chakri-nelluri
changshuchao
chaosaffe
chardch
charleszheng44
chendotjs
chenxuc
childsb
chrigl
chrislovecnm
chrisz100
chuckha
chuntaochen
clarketm
clarklee92
claurence
clyang82
cmluciano
cnadolny
code-sleuth
codenrhoden
cody-clark
coffeepac
copejon
corneliusweig
countspongebob
cstoku
cynepco3hahue
d-mo
daminisatya
danielSbastos
danielqsj
danninov
davidewatson
davidmirror-ops
davidz627
debgiles
deejross
deepak-vij
dejanb
dekkagaijin
desponda
dgoodwin
dianaabv
didicodes
dineshgovindasamy
djzager
dklyle
donghui12
doshyt
draveness
drekle
droot
drubin
dstrebel
dsu-igeek
dtaniwaki
duglin
dvonthenen
e-blackwelder
eagleusb
edisonxiang
egernst
eloyekunle
elweb9858
emedina
entro-pi
eparis
epk
erain
ereslibre
ericavonb
ericchiang
erikerlandson
erismaster
estroz
ethernetdan
evanap
evansheng
eve658
evillgenius75
f0rmiga
fejta
fenglixa
fengshunli
fengzixu
fgimenez
figo
filbranden
fisherxu
flaper87
fleeto
font
foxish
foxyriver
frankfarzan
freehan
frobware
gabbifish
gambol99
gaorong
gautierdelorme
gavinfish
geekygirldawn
gerred
gianarb
gianrubio
gkarthiks
glo-pena
gnarled-cipher
gnoam
gongguan
granular-ryanbonham
grayluck
grobie
grodrigues3
gtxu
gy95
gyliu513
h4ghhh
haibinxie
haiyanmeng
hanamantagoudvk
hangyan
hantaowang
harlowja
hasbro17
hasheddan
hbagdi
hchenxa
headcr4sh
helenfeng737
helight
hello2mao
heshamaboelmagd
hex108
hi-rustin
hickeyma
hidekazuna
hjacobs
hoegaarden
hogepodge
holmsten
hongchaodeng
honkiko
hosseinsalahi
houjun41544
hoyho
hpandeycodeit
hprateek43
hrishin
huangyuqi
huffmanca
hvaara
iXinqi
iamemilio
iamneha
ianlewis
ianychoi
ibrasho
ibzib
iheanyi1
ilya-zuyev
imkin
immutableT
immuzz
imroc
interma
ipuustin
irfanurrehman
ironcladlou
isaacdorfman
islinwb
ivan4th
j-griffith
jackkleeman
jacobsmith928
jaredbhatti
javier-b-perez
jdolitsky
jeffmendoza
jeffvance
jellonek
jennybuckley
jeremyeder
jgavinray
jherrera123
jhorwit2
jhvhs
jianglingxia
jiatongw
jiayingz
jimdaga
jingyih
jinnypark9393
jinsongo
jlewi
jluk
jmwurst
joadavis-g
johnSchnake
johnharris85
johnsonj
johscheuer
jonasrosland
joncwong
jonpulsifer
joonas
joshbranham
josiahbjorgaard
jpeach
jpreese
jqmichael
juan-lee
juandiegopalomino
juanfescobar
juanvallejo
julianvmodesto
jupblb
justin-chizer
jwforres
jygastaud
jyz0309
k-toyoda-pi
kacole2
karan
karataliu
karenhchu
kasramp
kbarnard10
kbasv
kbruner
kelseyhightower
kendallroden
kensipe
kgroschoff
kinarashah
kittenking
kkmsft
klaases
klaven
kosehy
krabhishek8260
krishchow
krisnova
krousey
krvaibhaw
krzysztof-jastrzebski
ksubrmnn
ktsakalozos
kumarvin123
kunal-kushwaha
lafh
lala123912
lbernail
lex111
lichuqiang
liranp
liu-cong
lixiang233
lixiaobing1
liyinan926
liztio
lledru
lmdaly
loburm
losipiuk
ltupin
lubinsz
lukaszgryglicki
lukaszo
luksa
lyzs90
m3ngyang
macaptain
madhanrm
makocchi-git
maplain
marcoceppi
mariantalla
mark-nc
markthink
marun
mashby2022
mattfarina
matthiasr
mattjmcnaughton
mattmoyer
mattymo
mauilion
maxdrib
mayankshah1607
mayocream
mbbroberg
mcrute
mcshooter
melodychn
mgdevstack
mgoodness
mhamdisemah
michaelkolber
michaelmdresser
michelleN
michmike
micw523
mikesplain
minbaev
mirandachrist
mirwan
miteshskj
mkhaas
mkorbi
mlmhl
mml
mohammedzee1000
monopole
mook-as
moonming
morengab
moriadry
morvencao
moshloop
mr-linus
mrajashree
mritunjaysharma394
mrkm4ntr
mrmrcoleman
msedzins
msheldyakov
mszostok
mtanino
mucahitkurt
muyangren2
mvortizr
mxinden
myan9
mysunshine92
mytunguyen
n3wscott
nader-ziada
nameYULI
nannancy
nebhale
nebril
necatican
nehaLohia27
nestorsalceda
ngtuna
nikopen
nilebox
nirarg
nirmalaagash
niulechuan
njuptlzf
noamran
nodo
nolancon
notchairmk
notpad
nowjean
nwoods3
obitech
oke-py
onyiny-ang
openstacker
oxddr
oz123
pancernik
parul5sahoo
pasqualet
paulbouwer
pbnj
perithompson
pgburt
phanama
phanimarupaka
philips
phoenixking25
php-coder
phumberdroz
phuongatemc
phyber
pierewoj
pigmej
pires
pjhwa
pmmalinov01
pontiyaraja
prachirp
prafull01
prameshj
prankul88
priyawadhwa
prksu
prydonius
ps882
pswica
ptux
pupapaik
pweil-
pydctw
qbl
qingsenLi
qnetter
qvicksilver
radhikapc
rajansandeep
rajatchopra
rajeshdeshpande02
rawkode
rbenzair
rbitia
rejoshed
rendhalver
resouer
ricolin
ritpanjw
riverzhang
rmenn
roberthbailey
robertojrojas
robinpercy
rojkov
rollony
rootfs
rootsongjc
rosti
rramkumar1
rrati
rudoi
runyontr
russellb
s-ito-ts
s04
s278gupt
sahilvv
saiyan86
sakshamsharma
samudralavamshi54
sanwishe
sarahnovotny
sbezverk
sboeuf
sbose78
scottrigby
screeley44
sebgoa
sedefsavas
sejr
sethmccombs
sethp-nr
sethpollack
sfzylad
shaileshsharan98
shashidharatd
shavidissa
shawn-hurley
sheerun
shekhar-rajak
shivi28
shiywang
shuaijinchao
shubheksha
shysank
sidharthsurana
simcard0000
simonswine
simplytunde
simrangupta234
siwyd
sjpotter
sjug
skrishna-unix
slaskawi
smourapina
soggiest
soniasingla
soulxu
spew
srampal
sreekaransrinath
stevemcquaid
steven-my
steveperry-53
stevesloka
stewart-yu
strigazi
sujaypillai
sumitranr
supriya-premkumar
swamymsft
tahsinrahman
tanjacky
tanjing2020
tanshanshan
taragu
tech-geek29
technosophos
tehcyx
tfogo
thandayuthapani
thecrudge
thejoycekung
timyinshi
tizhou86
tlereste
tnir
tomassedovic
tombarron
trutx
ttousai
tylerferrara
umohnani8
unguiculus
v-pap
vagababov
vdhanan
vedant-kakde
verult
vikaschoudhary16
viniciusbds
vinny-sabatini
vishakhanihore
vishh
vivekbagade
vjdhama
vkorbes
vllry
voigt
vonguard
vpickard
wahyuoi
wanghaoran1988
wangshiqi308
wangyx1992
warmchang
wattsteve
wawa0210
wfernandes
wgahnagl
wgliang
wilsonehusin
wk8
wonderfly
wongni
xiangpengzhao
xianlubird
xlgao-zju
xueweiz
xunpan
ydcool
yguo0905
yifan-gu
yiqigao217
yodahekinsew
yoojinl
yoonian
ysy2020
yuanying
yuexiao-wang
yuga711
yujuhong
yuxiaobo96
zehuaiWANG
zer0big
zestrells
zhangqx2010
zhangxiaoyu-zidif
zhaojizhuang
zhiguo-lu
zhlhahaha
zhouya0
zhuangqh
zjj2wry
zulandar
zyy19981018
```

```[tasklist]
### Tasks
- [x] Generate the list of inactive members
- [x] Send an email to dev@ and wait for 14days for people to raise exceptions
- [ ] Remove the inactive members from orgs and teams
- [ ] [Async] Remove inactive members from OWNERS files
```

**Comment by Ithrael** [comment]
I received an email and noticed that I am on this to-be-cleaned-up list. I just became a Kubernetes member [New membership for Ithrael](https://github.com/kubernetes/org/issues/4694) on January 18, 2024 , and upon reviewing the devstats for the past year, I have made some contributions as well. 
<img width="1551" alt="image" src="https://github.com/kubernetes/org/assets/38208715/bc980ae2-48fc-4df7-b295-c5658e1a5ad4">
<img width="1564" alt="image" src="https://github.com/kubernetes/org/assets/38208715/9067b6fe-0e6a-4e69-98cf-e394e4e60551">

**Comment by palnabarun** [comment]
@Ithrael -- thanks for the comment and your observations.

Rechecked the data. The error was due to how GitHub handles uppercase in usernames and an error in the [GitHub org manifest](https://github.com/kubernetes/org/pull/4695/files#r1468844690).

I have removed your name from the list as well as fixed the error.

**Comment by Elbehery** [comment]
hello ✋🏽 

i work on Etcd now, that why I should be removed ?

**Comment by chris-short** [comment]
I agree with @IanColdwater. Is there not a way to address security concerns with a `nogroup` esque permission scheme?

**Comment by mrbobbytables** [comment]
We can't make them org members and restrict access. While it may seem not be the best,  we have to prioritize the org. We can't add them to a specialty org or anything either because they must accept joining =/

**Comment by parispittman** [comment]
Would it be possible to add the usernames in a config file somewhere that would block abilities to run tests and other security measures without removing from the organization? 

I thought we discussed trying to preserve digital footprint during Steering in November 2019 when Brad Childs passed. I no longer have access to those notes. He is still in the organization: https://github.com/childsb

**Comment by mrbobbytables** [comment]
@parispittman that was likely before we put the policy in place regarding org cleanup. There is no good way to keep them in org without significant effort in prow. 

IMO - I'd add a page on k8s.dev for memorials and can link out to the individual cncf memorial pages, or have a note somewhere discoverable.

**Comment by davenull** [comment]
We should absolutely under no circumstances fail to understand that kubernetes is project *for* people *by* people. The contributors *are* k8s in many ways. A memorial pages for our departed friends is in my opinion a perfect way to enshrine that ideology.

**Comment by xianlubird** [comment]
Is it still too late to submit a few PRs or Issues now?

**Comment by WilliamDenniss** [comment]
I would like to remain a member please; I contributed to the [Certified Kubernetes Conformance Program](https://www.cncf.io/training/certification/software-conformance/) around the launch, and was recently appointed to the CNCF Governing Board as an alternate. Planning to step up my contributions in the k8s project this year.

**Comment by mrbobbytables** [comment]
@xianlubird @WilliamDenniss The exception period was more for people that have been active in other ways that we could not capture via DevStats. For those that it doesn't apply to, we prefer that people re-apply for org membership after demonstrating consistent activity.

**Comment by Elbehery** [comment]
Hello 

Please find my contributions to etcd below 

- https://github.com/etcd-io/bbolt/pull/659
- https://github.com/etcd-io/bbolt/pull/683
- https://github.com/etcd-io/bbolt/pull/682
- https://github.com/etcd-io/bbolt/pull/671
- https://github.com/etcd-io/bbolt/pull/635
- https://github.com/etcd-io/bbolt/pull/605
- https://github.com/etcd-io/bbolt/pull/624
- https://github.com/etcd-io/bbolt/pull/608
- https://github.com/etcd-io/bbolt/pull/606
- https://github.com/etcd-io/bbolt/pull/604
- https://github.com/etcd-io/bbolt/pull/598
- https://github.com/etcd-io/bbolt/pull/597
- https://github.com/etcd-io/bbolt/pull/596
- https://github.com/etcd-io/etcd/issues/14243
- https://github.com/etcd-io/etcd/pull/14242
- https://github.com/etcd-io/etcd/pull/14237
- https://github.com/etcd-io/etcd/pull/14221
- https://github.com/etcd-io/etcd/pull/14196
- https://github.com/etcd-io/etcd/pull/17388
- https://github.com/etcd-io/etcd/pull/17387

cc @soltysh

**Comment by mrbobbytables** [comment]
thanks Elbehery, will make sure it gets updated 👍

**Comment by palnabarun** [comment]
Hey @Elbehery, thanks for noting down your contributions to etcd. I have updated the list to remove your name.

When we initially generated the list, we took into cognizance etcd org members as contributors. Since etcd org migration to Kubernetes org machinery is in flux, there are some corner cases.

**Comment by KentaTada** [comment]
Hello

Could you add my name in the list again?
I'm one of reviewers for [kubernetes/system-validators](https://github.com/kubernetes/system-validators)
https://github.com/kubernetes/system-validators/blob/a0cb0d12f4d8ed79fa4ee4725ae179528dd2d522/OWNERS#L8
Currently, I am assigned to the below task.
https://github.com/kubernetes/system-validators/issues/36#issuecomment-1950933759
If I am removed from the Kubernetes GitHub organizations, it is difficult for me to keep on reviewer's activities to resolve Linux Kernel-related issues.
In addition to that, I'm the organizer of https://community.cncf.io/cloud-native-community-japan/ to widely adopt Kubernetes to Japanese companies.

**Comment by palnabarun** [comment]
Hi @KentaTada, you can always file a membership request to request to be added to the org citing your contributions.

However, to assure you, not having an org membership shouldn't block you from the issue that you mentioned.

**Comment by Xiao66666688** [comment]
大佬  有什么科技？
