### ISSUE TITLE
REQUEST: New kubernetes-milestone-maintainers membership for xmudrii

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/org#574]
### GitHub Username
@xmudrii

### Organization you are requesting membership in
kubernetes-milestone-maintainers

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
I'm already Kubernetes org member

### List of contributions to the Kubernetes project
* As a Bug Triage shadow for 1.14, I need to be able to modify milestone for issues and PRs

**Comment by nikhita** [comment]
@xmudrii can you create a PR to add yourself here? :) https://github.com/kubernetes/org/blob/9d184605dc1868781769becf605321d18407dddc/config/kubernetes/sig-release/teams.yaml#L2
